import { MogsAIProject, MinecraftPlatform, BuildTool } from '../types/mogsai';

export function createFabricItemMod(version: string = '1.21.1'): MogsAIProject {
  const javaVersion = 21;
  const modId = 'mogsitems';
  const modName = 'Mogs Custom Items';
  const packageName = 'com.mogsai.fabricmod';

  const fabricModJson = `{
  "schemaVersion": 1,
  "id": "${modId}",
  "version": "1.0.0",
  "name": "${modName}",
  "description": "Autonomous Fabric 1.21 Mod generated by MogsAI",
  "authors": ["MogsAI"],
  "license": "MIT",
  "environment": "*",
  "entrypoints": {
    "main": [
      "${packageName}.MogsFabricMod"
    ]
  },
  "depends": {
    "fabricloader": ">=0.16.0",
    "minecraft": "~${version}",
    "java": ">=21",
    "fabric-api": "*"
  }
}
`;

  const buildGradle = `plugins {
    id 'fabric-loom' version '1.7-SNAPSHOT'
    id 'maven-publish'
}

version = '1.0.0'
group = '${packageName}'

base {
    archivesName = '${modId}'
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(${javaVersion})
}

dependencies {
    minecraft "com.mojang:minecraft:${version}"
    mappings "net.fabricmc:yarn:${version}+build.1:v2"
    modImplementation "net.fabricmc:fabric-loader:0.16.5"
    modImplementation "net.fabricmc.fabric-api:fabric-api:0.100.8+${version}"
}

processResources {
    inputs.property "version", project.version
    filteringCharset "UTF-8"
    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}
`;

  const mainJava = `package ${packageName};

import net.fabricmc.api.ModInitializer;
import net.fabricmc.fabric.api.itemgroup.v1.ItemGroupEvents;
import net.minecraft.item.Item;
import net.minecraft.item.ItemGroups;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.util.Identifier;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class MogsFabricMod implements ModInitializer {
    public static final String MOD_ID = "${modId}";
    public static final Logger LOGGER = LoggerFactory.getLogger(MOD_ID);

    // Custom Item
    public static final Item RUBY_BLADE = Registry.register(
            Registries.ITEM,
            Identifier.of(MOD_ID, "ruby_blade"),
            new Item(new Item.Settings().maxCount(1).fireproof())
    );

    @Override
    public void onInitialize() {
        LOGGER.info("Initializing MogsCustomItems on Fabric 1.21!");

        // Add to Combat Item Group
        ItemGroupEvents.modifyEntriesEvent(ItemGroups.COMBAT).register(entries -> {
            entries.add(RUBY_BLADE);
        });
    }
}
`;

  return {
    id: 'proj_fabric_121',
    name: modName,
    description: 'Autonomous Fabric 1.21.x Item Mod with modern Fabric API registration.',
    platform: 'fabric',
    version,
    javaVersion,
    buildTool: 'gradle',
    currentMode: 'generate',
    createdAt: new Date().toISOString(),
    files: [
      { path: 'build.gradle', content: buildGradle, language: 'groovy' },
      { path: 'src/main/resources/fabric.mod.json', content: fabricModJson, language: 'json' },
      { path: `src/main/java/${packageName.replace(/\./g, '/')}/MogsFabricMod.java`, content: mainJava, language: 'java' },
      {
        path: 'README.md',
        content: `# ${modName}\n\nFabric 1.21.x mod created with MogsAI.\n\n### Build\nRun \`./gradlew build\` to generate the mod jar in \`build/libs/\`.`,
        language: 'markdown',
      },
    ],
    projectMap: {
      entryPoint: `${packageName}.MogsFabricMod`,
      commands: [],
      permissions: [],
      listeners: [{ name: 'ItemGroupEvents', events: ['modifyEntriesEvent'], description: 'Registers ruby blade to Combat tab' }],
      managers: [{ name: 'Registries.ITEM', responsibility: 'Fabric vanilla item registry' }],
      storage: { type: 'Minecraft Data Components', details: 'Uses 1.21 component item settings' },
      integrations: ['Fabric API 0.100.8', 'Fabric Loader 0.16.5'],
      architectureOverview: 'Fabric ModInitializer lifecycle registering custom items into Registries.ITEM.',
    },
    validationChecks: [
      { name: 'fabric.mod.json schema', status: 'passed', message: 'Schema v1 compliant with valid entrypoints.' },
      { name: 'Java 21 Toolchain', status: 'passed', message: 'Fabric 1.21 requires Java 21.' },
    ],
    debugHistory: [],
    reviewIssues: [],
    readme: '# Fabric Mod\nBuilt with MogsAI',
  };
}

export function createSkriptKitProject(): MogsAIProject {
  const skriptCode = `# ========================================================
# MogsKits - Advanced Autonomous Skript Script
# Target: Skript 2.9.x for Paper 1.21
# ========================================================

options:
    prefix: <#00f2fe>[MogsKits]<reset>
    pvp_cooldown: 3600 seconds
    archer_cooldown: 1800 seconds

# Command /kit
command /kit [<text>]:
    description: Open the Kit GUI or claim a kit directly
    permission: mogskits.use
    permission message: {@prefix} <red>You do not have permission to use kits!</red>
    trigger:
        if arg-1 is not set:
            openKitGui(player)
            stop

        if arg-1 is "pvp":
            claimKit(player, "pvp", "Warrior Kit", {@pvp_cooldown}, diamond sword named "<red>Warrior Blade</red>", 32 cooked beef)
        else if arg-1 is "archer":
            claimKit(player, "archer", "Archer Kit", {@archer_cooldown}, bow named "<aqua>Ranger Bow</aqua>", 64 arrow)
        else:
            send "{@prefix} <red>Unknown kit: %arg-1%</red>" to player

# Function to Open Modern Chest GUI
function openKitGui(p: player):
    create a gui with virtual chest inventory with 3 rows named "<bold><#00f2fe>Select a Kit</bold>":
        # Background fillers
        format gui slot (integers between 0 and 26) with gray stained glass pane named "&7"
        
        # Warrior Kit Slot 11
        format gui slot 11 with diamond sword named "<red><bold>Warrior Kit</bold></red>" with lore "&7Click to claim your combat gear!":
            close player's inventory
            execute player command "/kit pvp"

        # Archer Kit Slot 15
        format gui slot 15 with bow named "<aqua><bold>Archer Kit</bold></aqua>" with lore "&7Click to claim your ranger gear!":
            close player's inventory
            execute player command "/kit archer"
    open the last gui for {_p}

# Reusable Function to Claim Kits with Cooldowns
function claimKit(p: player, kitId: text, kitName: text, cd: timespan, items: items):
    set {_now} to now
    set {_lastClaim} to {kit::%{_kitId}%::%{_p}'s uuid%}

    if {_lastClaim} is set:
        set {_waited} to difference between {_lastClaim} and {_now}
        if {_waited} < {_cd}:
            set {_rem} to difference between {_cd} and {_waited}
            send "{@prefix} <yellow>You must wait <gold>%{_rem}%</gold> before claiming this kit again!</yellow>" to {_p}
            play sound "entity.villager.no" at {_p}
            stop

    # Give Items
    give {_items} to {_p}
    set {kit::%{_kitId}%::%{_p}'s uuid%} to {_now}
    send "{@prefix} <green>You claimed the <aqua>%{_kitName}%</aqua>!</green>" to {_p}
    play sound "entity.player.levelup" at {_p}
`;

  return {
    id: 'proj_skript_kits',
    name: 'MogsKits Skript',
    description: 'High-performance Skript script with GUI, cooldown variables, and sound effects.',
    platform: 'skript',
    version: '1.21.1',
    javaVersion: 21,
    buildTool: 'none',
    currentMode: 'generate',
    createdAt: new Date().toISOString(),
    files: [
      { path: 'plugins/Skript/scripts/kits.sk', content: skriptCode, language: 'skript' },
      {
        path: 'README.md',
        content: `# MogsKits Skript\nDrop \`kits.sk\` into \`plugins/Skript/scripts/\` and reload with \`/sk reload kits\`.`,
        language: 'markdown',
      },
    ],
    projectMap: {
      entryPoint: 'plugins/Skript/scripts/kits.sk',
      commands: [{ name: 'kit', permission: 'mogskits.use', description: 'Opens GUI or claims kit', usage: '/kit [name]' }],
      permissions: [{ node: 'mogskits.use', description: 'Use kit system', default: 'true' }],
      listeners: [],
      managers: [{ name: 'openKitGui function', responsibility: 'Constructs chest GUI' }, { name: 'claimKit function', responsibility: 'Validates cooldown and distributes items' }],
      storage: { type: 'Skript Variables {kit::*}', details: 'Persistent server variables' },
      integrations: ['Skript 2.9+'],
      architectureOverview: 'Event & Function based Skript script with virtual inventory GUI formatting.',
    },
    validationChecks: [
      { name: 'Skript Syntax & Indentation', status: 'passed', message: 'Valid 4-space tab indentation and trigger blocks.' },
      { name: 'GUI Virtual Inventory Format', status: 'passed', message: 'Modern virtual chest inventory syntax compliant.' },
    ],
    debugHistory: [],
    reviewIssues: [],
    readme: '# Skript Kit System\nReady for Skript 2.9 on Paper 1.21',
  };
}

export function createDatapackProject(): MogsAIProject {
  const packMcmeta = `{
  "pack": {
    "pack_format": 48,
    "description": "Autonomous Datapack for Minecraft 1.21 by MogsAI"
  }
}
`;

  const loadMcFunction = `tellraw @a [{"text":"[MogsAI] ","color":"aqua","bold":true},{"text":"Datapack loaded successfully on 1.21!","color":"green"}]
scoreboard objectives add mogs_timer dummy
scoreboard objectives add mogs_kills playerKillCount
`;

  const tickMcFunction = `# Runs every tick (20 times per second)
execute as @a[scores={mogs_kills=1..}] run function mogs:on_kill
`;

  const onKillMcFunction = `tellraw @s [{"text":"[MogsAI] ","color":"gold"},{"text":"Kill recorded! +100 XP rewarded.","color":"yellow"}]
experience add @s 100 points
scoreboard players reset @s mogs_kills
`;

  return {
    id: 'proj_datapack_121',
    name: 'MogsDatapack 1.21',
    description: 'Vanilla Minecraft 1.21 Datapack with pack.mcmeta format 48, tick, load, and custom scoreboards.',
    platform: 'datapack',
    version: '1.21.1',
    javaVersion: 21,
    buildTool: 'none',
    currentMode: 'generate',
    createdAt: new Date().toISOString(),
    files: [
      { path: 'pack.mcmeta', content: packMcmeta, language: 'json' },
      { path: 'data/minecraft/tags/function/load.json', content: '{\n  "values": ["mogs:load"]\n}', language: 'json' },
      { path: 'data/minecraft/tags/function/tick.json', content: '{\n  "values": ["mogs:tick"]\n}', language: 'json' },
      { path: 'data/mogs/function/load.mcfunction', content: loadMcFunction, language: 'markdown' },
      { path: 'data/mogs/function/tick.mcfunction', content: tickMcFunction, language: 'markdown' },
      { path: 'data/mogs/function/on_kill.mcfunction', content: onKillMcFunction, language: 'markdown' },
    ],
    projectMap: {
      entryPoint: 'data/mogs/function/load.mcfunction',
      commands: [],
      permissions: [],
      listeners: [{ name: 'tick.json', events: ['minecraft:tick'], description: 'Runs every game tick' }],
      managers: [{ name: 'Scoreboard Objectives', responsibility: 'Tracks player kills and timers' }],
      storage: { type: 'Minecraft Scoreboard Dummies', details: 'Vanilla NBT scoreboard persistence' },
      integrations: ['Vanilla 1.21 Datapack Engine'],
      architectureOverview: 'Standard 1.21 datapack structure with tick/load tags and namespaced functions.',
    },
    validationChecks: [
      { name: 'pack.mcmeta pack_format', status: 'passed', message: 'pack_format 48 matches Minecraft 1.21.' },
      { name: 'Namespaced JSON Tags', status: 'passed', message: 'Load & Tick tags properly structured.' },
    ],
    debugHistory: [],
    reviewIssues: [],
    readme: '# Datapack 1.21\nPlace in world/datapacks/ folder and run /reload',
  };
}

export function createPaperKitProject(version: string = '1.21.4', buildTool: BuildTool = 'gradle'): MogsAIProject {
  const javaVersion = 21;
  const projectName = 'MogsKits';
  const packageName = 'com.mogsai.kits';

  const gradleFile = `plugins {
    id 'java'
}

group = '${packageName}'
version = '1.0.0-SNAPSHOT'
description = 'Production-ready Paper 1.21 Kit Plugin generated by MogsAI'

java {
    toolchain.languageVersion = JavaLanguageVersion.of(${javaVersion})
}

repositories {
    mavenCentral()
    maven {
        name = "papermc-repo"
        url = "https://repo.papermc.io/repository/maven-public/"
    }
    maven {
        name = "sonatype"
        url = "https://oss.sonatype.org/content/groups/public/"
    }
    maven {
        name = "jitpack"
        url = "https://jitpack.io"
    }
}

dependencies {
    compileOnly("io.papermc.paper:paper-api:${version}-R0.1-SNAPSHOT")
    compileOnly("com.github.MilkBowl:VaultAPI:1.7.1")
    compileOnly("me.clip:placeholderapi:2.11.6")
    testImplementation("org.junit.jupiter:junit-jupiter:5.10.2")
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = ${javaVersion}
}

test {
    useJUnitPlatform()
}
`;

  const pomFile = `<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>${packageName}</groupId>
    <artifactId>${projectName}</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>jar</packaging>

    <properties>
        <java.version>${javaVersion}</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <repositories>
        <repository>
            <id>papermc</id>
            <url>https://repo.papermc.io/repository/maven-public/</url>
        </repository>
        <repository>
            <id>jitpack</id>
            <url>https://jitpack.io</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>io.papermc.paper</groupId>
            <artifactId>paper-api</artifactId>
            <version>${version}-R0.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.github.MilkBowl</groupId>
            <artifactId>VaultAPI</artifactId>
            <version>1.7.1</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.13.0</version>
                <configuration>
                    <source>\${java.version}</source>
                    <target>\${java.version}</target>
                    <release>\${java.version}</release>
                </configuration>
            </plugin>
        </plugins>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
    </build>
</project>
`;

  const paperPluginYml = `name: ${projectName}
version: '1.0.0'
main: ${packageName}.KitPlugin
api-version: '1.21'
author: MogsAI
description: Advanced Paper 1.21 Kit plugin with GUI, PDC storage, cooldowns, and permissions.
folia-supported: true

commands:
  kit:
    description: Opens the kit selection GUI or claims a kit
    permission: mogskits.use
    usage: /kit [kitName]
  kitadmin:
    description: Administration commands for kits
    permission: mogskits.admin
    usage: /kitadmin <reload|resetcooldown|create>

permissions:
  mogskits.use:
    description: Allows accessing the kit system and GUI
    default: true
  mogskits.kit.pvp:
    description: Access to the Warrior kit
    default: true
  mogskits.kit.archer:
    description: Access to the Archer kit
    default: true
  mogskits.kit.vip:
    description: Access to the VIP kit
    default: op
  mogskits.admin:
    description: Access to reload and administration
    default: op
`;

  const configYml = `# MogsKits Configuration File
# Modern Adventure MiniMessage formatting is supported (<gradient>, <color>, <bold>)

prefix: "<gradient:#00f2fe:#4facfe>[MogsKits]</gradient> "

settings:
  cooldown-bypass-permission: "mogskits.bypass.cooldown"
  close-gui-on-claim: true
  play-sound-on-claim: true
  sound-name: "ENTITY_PLAYER_LEVELUP"

messages:
  no-permission: "<red>You don't have permission to use this kit!</red>"
  cooldown-active: "<yellow>You must wait <gold>{time}</gold> before claiming this kit again.</yellow>"
  kit-claimed: "<green>Successfully claimed the <aqua>{kit}</aqua> kit!</green>"
  inventory-full: "<red>Your inventory is full! Some items dropped to the ground.</red>"
  kit-not-found: "<red>The specified kit does not exist.</red>"
  reloaded: "<green>MogsKits configuration reloaded successfully!</green>"

# Kit Definitions
kits:
  pvp:
    display-name: "<gradient:#ff0844:#ffb199>Warrior Kit</gradient>"
    icon: "DIAMOND_SWORD"
    slot: 11
    permission: "mogskits.kit.pvp"
    cooldown-seconds: 3600
    description:
      - "<gray>Standard combat kit for arena duels.</gray>"
      - "<gray>Cooldown: <gold>1 Hour</gold></gray>"
    items:
      - material: "DIAMOND_SWORD"
        amount: 1
        name: "<red>Warrior Blade</red>"
        enchantments:
          SHARPNESS: 2
          UNBREAKING: 1
      - material: "COOKED_BEEF"
        amount: 32
      - material: "GOLDEN_APPLE"
        amount: 2

  archer:
    display-name: "<gradient:#43e97b:#38f9d7>Ranger Kit</gradient>"
    icon: "BOW"
    slot: 13
    permission: "mogskits.kit.archer"
    cooldown-seconds: 1800
    description:
      - "<gray>Ranged combat kit with custom bow.</gray>"
      - "<gray>Cooldown: <gold>30 Minutes</gold></gray>"
    items:
      - material: "BOW"
        amount: 1
        name: "<aqua>Ranger Longbow</aqua>"
        enchantments:
          POWER: 3
          INFINITY: 1
      - material: "ARROW"
        amount: 1
      - material: "CHAINMAIL_CHESTPLATE"
        amount: 1

  vip:
    display-name: "<gradient:#f6d365:#fda085>VIP Legend Kit</gradient>"
    icon: "NETHERITE_INGOT"
    slot: 15
    permission: "mogskits.kit.vip"
    cooldown-seconds: 86400
    description:
      - "<gold>Exclusive kit for VIP supporters.</gold>"
      - "<gray>Cooldown: <gold>24 Hours</gold></gray>"
    items:
      - material: "NETHERITE_SWORD"
        amount: 1
        name: "<yellow>Legendary Claymore</yellow>"
        enchantments:
          SHARPNESS: 4
          FIRE_ASPECT: 2
      - material: "ENCHANTED_GOLDEN_APPLE"
        amount: 1
      - material: "DIAMOND"
        amount: 8
`;

  const mainPluginJava = `package ${packageName};

import ${packageName}.command.KitCommand;
import ${packageName}.command.KitAdminCommand;
import ${packageName}.listener.KitGuiListener;
import ${packageName}.manager.CooldownManager;
import ${packageName}.manager.KitManager;
import ${packageName}.storage.PlayerDataStorage;
import ${packageName}.util.MessageUtil;
import org.bukkit.plugin.java.JavaPlugin;

import java.io.File;

/**
 * MogsKits - Production-grade Paper 1.21 Kit Plugin
 * Built autonomously with MogsAI Architecture Engine.
 */
public final class KitPlugin extends JavaPlugin {

    private static KitPlugin instance;
    private KitManager kitManager;
    private CooldownManager cooldownManager;
    private PlayerDataStorage dataStorage;

    @Override
    public void onEnable() {
        instance = this;

        // 1. Initialize configuration
        saveDefaultConfig();

        // 2. Initialize Storage & Managers
        File dataFolder = new File(getDataFolder(), "playerdata");
        if (!dataFolder.exists()) {
            dataFolder.mkdirs();
        }
        this.dataStorage = new PlayerDataStorage(this, dataFolder);
        this.cooldownManager = new CooldownManager(this, dataStorage);
        this.kitManager = new KitManager(this);
        this.kitManager.loadKits();

        // 3. Register Events
        getServer().getPluginManager().registerEvents(new KitGuiListener(this), this);

        // 4. Register Commands
        if (getCommand("kit") != null) {
            getCommand("kit").setExecutor(new KitCommand(this));
            getCommand("kit").setTabCompleter(new KitCommand(this));
        }
        if (getCommand("kitadmin") != null) {
            getCommand("kitadmin").setExecutor(new KitAdminCommand(this));
            getCommand("kitadmin").setTabCompleter(new KitAdminCommand(this));
        }

        getLogger().info("MogsKits has been successfully enabled on Paper 1.21!");
    }

    @Override
    public void onDisable() {
        if (dataStorage != null) {
            dataStorage.saveAllSync();
        }
        getLogger().info("MogsKits has been safely disabled. Player data saved.");
    }

    public void reloadPlugin() {
        reloadConfig();
        kitManager.loadKits();
        getLogger().info("Configuration reloaded.");
    }

    public static KitPlugin getInstance() {
        return instance;
    }

    public KitManager getKitManager() {
        return kitManager;
    }

    public CooldownManager getCooldownManager() {
        return cooldownManager;
    }

    public PlayerDataStorage getDataStorage() {
        return dataStorage;
    }
}
`;

  const kitModelJava = `package ${packageName}.model;

import net.kyori.adventure.text.Component;
import org.bukkit.Material;
import org.bukkit.inventory.ItemStack;

import java.util.List;

public class Kit {
    private final String id;
    private final Component displayName;
    private final Material icon;
    private final int slot;
    private final String permission;
    private final long cooldownSeconds;
    private final List<Component> description;
    private final List<ItemStack> items;

    public Kit(String id, Component displayName, Material icon, int slot, String permission,
               long cooldownSeconds, List<Component> description, List<ItemStack> items) {
        this.id = id;
        this.displayName = displayName;
        this.icon = icon;
        this.slot = slot;
        this.permission = permission;
        this.cooldownSeconds = cooldownSeconds;
        this.description = description;
        this.items = items;
    }

    public String getId() {
        return id;
    }

    public Component getDisplayName() {
        return displayName;
    }

    public Material getIcon() {
        return icon;
    }

    public int getSlot() {
        return slot;
    }

    public String getPermission() {
        return permission;
    }

    public long getCooldownSeconds() {
        return cooldownSeconds;
    }

    public List<Component> getDescription() {
        return description;
    }

    public List<ItemStack> getItems() {
        return items;
    }
}
`;

  const kitManagerJava = `package ${packageName}.manager;

import ${packageName}.KitPlugin;
import ${packageName}.model.Kit;
import ${packageName}.util.MessageUtil;
import net.kyori.adventure.text.Component;
import org.bukkit.Material;
import org.bukkit.configuration.ConfigurationSection;
import org.bukkit.enchantments.Enchantment;
import org.bukkit.entity.Player;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.meta.ItemMeta;

import java.util.*;

public class KitManager {

    private final KitPlugin plugin;
    private final Map<String, Kit> kits = new LinkedHashMap<>();

    public KitManager(KitPlugin plugin) {
        this.plugin = plugin;
    }

    public void loadKits() {
        kits.clear();
        ConfigurationSection section = plugin.getConfig().getConfigurationSection("kits");
        if (section == null) return;

        for (String key : section.getKeys(false)) {
            ConfigurationSection kitSec = section.getConfigurationSection(key);
            if (kitSec == null) continue;

            String rawName = kitSec.getString("display-name", key);
            Component displayName = MessageUtil.parse(rawName);
            Material icon = Material.matchMaterial(kitSec.getString("icon", "CHEST"));
            if (icon == null) icon = Material.CHEST;
            int slot = kitSec.getInt("slot", 10);
            String permission = kitSec.getString("permission", "mogskits.kit." + key);
            long cooldown = kitSec.getLong("cooldown-seconds", 3600);

            List<Component> lore = new ArrayList<>();
            for (String line : kitSec.getStringList("description")) {
                lore.add(MessageUtil.parse(line));
            }

            List<ItemStack> items = new ArrayList<>();
            List<Map<?, ?>> itemMaps = kitSec.getMapList("items");
            for (Map<?, ?> itemMap : itemMaps) {
                String matStr = String.valueOf(itemMap.get("material"));
                Material mat = Material.matchMaterial(matStr);
                if (mat == null) mat = Material.DIRT;

                int amount = 1;
                if (itemMap.containsKey("amount")) {
                    amount = ((Number) itemMap.get("amount")).intValue();
                }

                ItemStack stack = new ItemStack(mat, amount);
                ItemMeta meta = stack.getItemMeta();
                if (meta != null) {
                    if (itemMap.containsKey("name")) {
                        meta.displayName(MessageUtil.parse(String.valueOf(itemMap.get("name"))));
                    }
                    if (itemMap.containsKey("enchantments") && itemMap.get("enchantments") instanceof Map<?, ?> encMap) {
                        for (Map.Entry<?, ?> entry : encMap.entrySet()) {
                            try {
                                Enchantment enc = Enchantment.getByName(String.valueOf(entry.getKey()).toUpperCase());
                                if (enc != null) {
                                    meta.addEnchant(enc, ((Number) entry.getValue()).intValue(), true);
                                }
                            } catch (Exception ignored) {}
                        }
                    }
                    stack.setItemMeta(meta);
                }
                items.add(stack);
            }

            Kit kit = new Kit(key, displayName, icon, slot, permission, cooldown, lore, items);
            kits.put(key.toLowerCase(), kit);
        }
        plugin.getLogger().info("Loaded " + kits.size() + " kit(s).");
    }

    public Optional<Kit> getKit(String id) {
        return Optional.ofNullable(kits.get(id.toLowerCase()));
    }

    public Collection<Kit> getAllKits() {
        return Collections.unmodifiableCollection(kits.values());
    }

    public boolean giveKit(Player player, Kit kit) {
        for (ItemStack item : kit.getItems()) {
            HashMap<Integer, ItemStack> leftover = player.getInventory().addItem(item.clone());
            if (!leftover.isEmpty()) {
                for (ItemStack drop : leftover.values()) {
                    player.getWorld().dropItemNaturally(player.getLocation(), drop);
                }
                player.sendMessage(MessageUtil.parse(plugin.getConfig().getString("messages.inventory-full")));
            }
        }
        return true;
    }
}
`;

  const cooldownManagerJava = `package ${packageName}.manager;

import ${packageName}.KitPlugin;
import ${packageName}.model.Kit;
import ${packageName}.storage.PlayerDataStorage;
import org.bukkit.entity.Player;

import java.util.UUID;

public class CooldownManager {

    private final KitPlugin plugin;
    private final PlayerDataStorage storage;

    public CooldownManager(KitPlugin plugin, PlayerDataStorage storage) {
        this.plugin = plugin;
        this.storage = storage;
    }

    public boolean isOnCooldown(Player player, Kit kit) {
        if (player.hasPermission("mogskits.bypass.cooldown") || player.hasPermission("mogskits.admin")) {
            return false;
        }

        long lastClaim = storage.getLastClaimTime(player.getUniqueId(), kit.getId());
        long now = System.currentTimeMillis();
        long diffSeconds = (now - lastClaim) / 1000;

        return diffSeconds < kit.getCooldownSeconds();
    }

    public long getRemainingSeconds(Player player, Kit kit) {
        long lastClaim = storage.getLastClaimTime(player.getUniqueId(), kit.getId());
        long now = System.currentTimeMillis();
        long diffSeconds = (now - lastClaim) / 1000;
        long remaining = kit.getCooldownSeconds() - diffSeconds;
        return Math.max(0, remaining);
    }

    public void setClaimed(Player player, Kit kit) {
        storage.setLastClaimTime(player.getUniqueId(), kit.getId(), System.currentTimeMillis());
    }

    public void resetCooldown(UUID uuid, String kitId) {
        storage.setLastClaimTime(uuid, kitId, 0);
    }

    public String formatRemaining(long seconds) {
        if (seconds < 60) return seconds + "s";
        long minutes = seconds / 60;
        long hours = minutes / 60;
        if (hours > 0) {
            return hours + "h " + (minutes % 60) + "m";
        }
        return minutes + "m " + (seconds % 60) + "s";
    }
}
`;

  const guiHolderJava = `package ${packageName}.gui;

import org.bukkit.inventory.Inventory;
import org.bukkit.inventory.InventoryHolder;

public class KitGuiHolder implements InventoryHolder {
    private Inventory inventory;

    @Override
    public Inventory getInventory() {
        return inventory;
    }

    public void setInventory(Inventory inventory) {
        this.inventory = inventory;
    }
}
`;

  const kitGuiJava = `package ${packageName}.gui;

import ${packageName}.KitPlugin;
import ${packageName}.model.Kit;
import ${packageName}.util.MessageUtil;
import net.kyori.adventure.text.Component;
import org.bukkit.Bukkit;
import org.bukkit.Material;
import org.bukkit.NamespacedKey;
import org.bukkit.entity.Player;
import org.bukkit.inventory.Inventory;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.meta.ItemMeta;
import org.bukkit.persistence.PersistentDataType;

import java.util.ArrayList;
import java.util.List;

public class KitGui {

    public static final NamespacedKey KIT_KEY = new NamespacedKey(KitPlugin.getInstance(), "gui_kit_id");

    public static void open(Player player) {
        KitPlugin plugin = KitPlugin.getInstance();
        KitGuiHolder holder = new KitGuiHolder();
        Component title = MessageUtil.parse("<gradient:#00f2fe:#4facfe><bold>Select a Kit</bold></gradient>");
        Inventory inv = Bukkit.createInventory(holder, 27, title);
        holder.setInventory(inv);

        // Fill background with dark stained glass
        ItemStack filler = new ItemStack(Material.GRAY_STAINED_GLASS_PANE);
        ItemMeta fillMeta = filler.getItemMeta();
        if (fillMeta != null) {
            fillMeta.displayName(Component.empty());
            filler.setItemMeta(fillMeta);
        }
        for (int i = 0; i < 27; i++) {
            inv.setItem(i, filler);
        }

        // Place kits
        for (Kit kit : plugin.getKitManager().getAllKits()) {
            ItemStack icon = new ItemStack(kit.getIcon());
            ItemMeta meta = icon.getItemMeta();
            if (meta != null) {
                meta.displayName(kit.getDisplayName());
                List<Component> lore = new ArrayList<>(kit.getDescription());
                lore.add(Component.empty());

                boolean hasPerm = player.hasPermission(kit.getPermission());
                boolean onCd = plugin.getCooldownManager().isOnCooldown(player, kit);

                if (!hasPerm) {
                    lore.add(MessageUtil.parse("<red>✖ Locked - No Permission</red>"));
                } else if (onCd) {
                    long remaining = plugin.getCooldownManager().getRemainingSeconds(player, kit);
                    lore.add(MessageUtil.parse("<yellow>⏳ Cooldown: " + plugin.getCooldownManager().formatRemaining(remaining) + "</yellow>"));
                } else {
                    lore.add(MessageUtil.parse("<green>✔ Click to Claim!</green>"));
                }

                meta.lore(lore);
                // Mark with PDC
                meta.getPersistentDataContainer().set(KIT_KEY, PersistentDataType.STRING, kit.getId());
                icon.setItemMeta(meta);
            }
            if (kit.getSlot() >= 0 && kit.getSlot() < 27) {
                inv.setItem(kit.getSlot(), icon);
            }
        }

        player.openInventory(inv);
    }
}
`;

  const kitGuiListenerJava = `package ${packageName}.listener;

import ${packageName}.KitPlugin;
import ${packageName}.gui.KitGui;
import ${packageName}.gui.KitGuiHolder;
import ${packageName}.model.Kit;
import ${packageName}.util.MessageUtil;
import org.bukkit.Sound;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.inventory.InventoryClickEvent;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.meta.ItemMeta;
import org.bukkit.persistence.PersistentDataType;

public class KitGuiListener implements Listener {

    private final KitPlugin plugin;

    public KitGuiListener(KitPlugin plugin) {
        this.plugin = plugin;
    }

    @EventHandler
    public void onInventoryClick(InventoryClickEvent event) {
        if (!(event.getInventory().getHolder() instanceof KitGuiHolder)) {
            return;
        }

        // Cancel all clicks in kit GUI to prevent item theft
        event.setCancelled(true);

        if (!(event.getWhoClicked() instanceof Player player)) return;
        ItemStack clicked = event.getCurrentItem();
        if (clicked == null || !clicked.hasItemMeta()) return;

        ItemMeta meta = clicked.getItemMeta();
        if (!meta.getPersistentDataContainer().has(KitGui.KIT_KEY, PersistentDataType.STRING)) {
            return;
        }

        String kitId = meta.getPersistentDataContainer().get(KitGui.KIT_KEY, PersistentDataType.STRING);
        if (kitId == null) return;

        Kit kit = plugin.getKitManager().getKit(kitId).orElse(null);
        if (kit == null) {
            player.sendMessage(MessageUtil.parse(plugin.getConfig().getString("messages.kit-not-found")));
            return;
        }

        if (!player.hasPermission(kit.getPermission())) {
            player.sendMessage(MessageUtil.parse(plugin.getConfig().getString("messages.no-permission")));
            player.playSound(player.getLocation(), Sound.ENTITY_VILLAGER_NO, 1.0f, 1.0f);
            return;
        }

        if (plugin.getCooldownManager().isOnCooldown(player, kit)) {
            long remaining = plugin.getCooldownManager().getRemainingSeconds(player, kit);
            String formatted = plugin.getCooldownManager().formatRemaining(remaining);
            String msg = plugin.getConfig().getString("messages.cooldown-active", "").replace("{time}", formatted);
            player.sendMessage(MessageUtil.parse(msg));
            player.playSound(player.getLocation(), Sound.BLOCK_CHEST_LOCKED, 1.0f, 1.0f);
            return;
        }

        // Claim kit
        plugin.getKitManager().giveKit(player, kit);
        plugin.getCooldownManager().setClaimed(player, kit);

        String msg = plugin.getConfig().getString("messages.kit-claimed", "").replace("{kit}", kit.getId());
        player.sendMessage(MessageUtil.parse(msg));

        if (plugin.getConfig().getBoolean("settings.play-sound-on-claim", true)) {
            player.playSound(player.getLocation(), Sound.ENTITY_PLAYER_LEVELUP, 1.0f, 1.2f);
        }

        if (plugin.getConfig().getBoolean("settings.close-gui-on-claim", true)) {
            player.closeInventory();
        } else {
            KitGui.open(player); // Refresh
        }
    }
}
`;

  const kitCommandJava = `package ${packageName}.command;

import ${packageName}.KitPlugin;
import ${packageName}.gui.KitGui;
import ${packageName}.model.Kit;
import ${packageName}.util.MessageUtil;
import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;
import org.bukkit.command.TabCompleter;
import org.bukkit.entity.Player;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.util.ArrayList;
import java.util.List;

public class KitCommand implements CommandExecutor, TabCompleter {

    private final KitPlugin plugin;

    public KitCommand(KitPlugin plugin) {
        this.plugin = plugin;
    }

    @Override
    public boolean onCommand(@NotNull CommandSender sender, @NotNull Command command, @NotNull String label, @NotNull String[] args) {
        if (!(sender instanceof Player player)) {
            sender.sendMessage("This command can only be executed by players.");
            return true;
        }

        if (!player.hasPermission("mogskits.use")) {
            player.sendMessage(MessageUtil.parse(plugin.getConfig().getString("messages.no-permission")));
            return true;
        }

        if (args.length == 0) {
            KitGui.open(player);
            return true;
        }

        String kitName = args[0];
        Kit kit = plugin.getKitManager().getKit(kitName).orElse(null);
        if (kit == null) {
            player.sendMessage(MessageUtil.parse(plugin.getConfig().getString("messages.kit-not-found")));
            return true;
        }

        if (!player.hasPermission(kit.getPermission())) {
            player.sendMessage(MessageUtil.parse(plugin.getConfig().getString("messages.no-permission")));
            return true;
        }

        if (plugin.getCooldownManager().isOnCooldown(player, kit)) {
            long remaining = plugin.getCooldownManager().getRemainingSeconds(player, kit);
            String formatted = plugin.getCooldownManager().formatRemaining(remaining);
            String msg = plugin.getConfig().getString("messages.cooldown-active", "").replace("{time}", formatted);
            player.sendMessage(MessageUtil.parse(msg));
            return true;
        }

        plugin.getKitManager().giveKit(player, kit);
        plugin.getCooldownManager().setClaimed(player, kit);

        String msg = plugin.getConfig().getString("messages.kit-claimed", "").replace("{kit}", kit.getId());
        player.sendMessage(MessageUtil.parse(msg));
        return true;
    }

    @Override
    public @Nullable List<String> onTabComplete(@NotNull CommandSender sender, @NotNull Command command, @NotNull String label, @NotNull String[] args) {
        List<String> completions = new ArrayList<>();
        if (args.length == 1) {
            for (Kit kit : plugin.getKitManager().getAllKits()) {
                if (sender.hasPermission(kit.getPermission()) && kit.getId().toLowerCase().startsWith(args[0].toLowerCase())) {
                    completions.add(kit.getId());
                }
            }
        }
        return completions;
    }
}
`;

  const kitAdminCommandJava = `package ${packageName}.command;

import ${packageName}.KitPlugin;
import ${packageName}.util.MessageUtil;
import org.bukkit.Bukkit;
import org.bukkit.OfflinePlayer;
import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;
import org.bukkit.command.TabCompleter;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class KitAdminCommand implements CommandExecutor, TabCompleter {

    private final KitPlugin plugin;

    public KitAdminCommand(KitPlugin plugin) {
        this.plugin = plugin;
    }

    @Override
    public boolean onCommand(@NotNull CommandSender sender, @NotNull Command command, @NotNull String label, @NotNull String[] args) {
        if (!sender.hasPermission("mogskits.admin")) {
            sender.sendMessage(MessageUtil.parse(plugin.getConfig().getString("messages.no-permission")));
            return true;
        }

        if (args.length == 0) {
            sender.sendMessage(MessageUtil.parse("<yellow>Usage: /kitadmin <reload|resetcooldown> [player] [kit]</yellow>"));
            return true;
        }

        if (args[0].equalsIgnoreCase("reload")) {
            plugin.reloadPlugin();
            sender.sendMessage(MessageUtil.parse(plugin.getConfig().getString("messages.reloaded")));
            return true;
        }

        if (args[0].equalsIgnoreCase("resetcooldown") && args.length >= 3) {
            OfflinePlayer target = Bukkit.getOfflinePlayer(args[1]);
            String kitId = args[2];
            plugin.getCooldownManager().resetCooldown(target.getUniqueId(), kitId);
            sender.sendMessage(MessageUtil.parse("<green>Reset cooldown for " + target.getName() + " on kit " + kitId + ".</green>"));
            return true;
        }

        sender.sendMessage(MessageUtil.parse("<red>Invalid syntax. Use: /kitadmin <reload|resetcooldown></red>"));
        return true;
    }

    @Override
    public @Nullable List<String> onTabComplete(@NotNull CommandSender sender, @NotNull Command command, @NotNull String label, @NotNull String[] args) {
        if (args.length == 1) {
            return Arrays.asList("reload", "resetcooldown");
        }
        return null;
    }
}
`;

  const playerDataStorageJava = `package ${packageName}.storage;

import ${packageName}.KitPlugin;
import org.bukkit.configuration.file.YamlConfiguration;

import java.io.File;
import java.io.IOException;
import java.util.Map;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Thread-safe Player Data storage using asynchronous writes to avoid server tick stalls.
 */
public class PlayerDataStorage {

    private final KitPlugin plugin;
    private final File dataFolder;
    private final Map<UUID, YamlConfiguration> cache = new ConcurrentHashMap<>();

    public PlayerDataStorage(KitPlugin plugin, File dataFolder) {
        this.plugin = plugin;
        this.dataFolder = dataFolder;
    }

    private File getFile(UUID uuid) {
        return new File(dataFolder, uuid.toString() + ".yml");
    }

    public synchronized YamlConfiguration getPlayerData(UUID uuid) {
        return cache.computeIfAbsent(uuid, id -> {
            File f = getFile(id);
            if (f.exists()) {
                return YamlConfiguration.loadConfiguration(f);
            }
            return new YamlConfiguration();
        });
    }

    public long getLastClaimTime(UUID uuid, String kitId) {
        YamlConfiguration config = getPlayerData(uuid);
        return config.getLong("cooldowns." + kitId.toLowerCase(), 0L);
    }

    public void setLastClaimTime(UUID uuid, String kitId, long timestamp) {
        YamlConfiguration config = getPlayerData(uuid);
        config.set("cooldowns." + kitId.toLowerCase(), timestamp);
        saveAsync(uuid);
    }

    public void saveAsync(UUID uuid) {
        plugin.getServer().getScheduler().runTaskAsynchronously(plugin, () -> {
            YamlConfiguration config = cache.get(uuid);
            if (config != null) {
                try {
                    config.save(getFile(uuid));
                } catch (IOException e) {
                    plugin.getLogger().warning("Failed to save data for " + uuid + ": " + e.getMessage());
                }
            }
        });
    }

    public void saveAllSync() {
        for (Map.Entry<UUID, YamlConfiguration> entry : cache.entrySet()) {
            try {
                entry.getValue().save(getFile(entry.getKey()));
            } catch (IOException e) {
                plugin.getLogger().warning("Failed to save data for " + entry.getKey());
            }
        }
    }
}
`;

  const messageUtilJava = `package ${packageName}.util;

import net.kyori.adventure.text.Component;
import net.kyori.adventure.text.minimessage.MiniMessage;

public final class MessageUtil {

    private static final MiniMessage MINI_MESSAGE = MiniMessage.miniMessage();

    private MessageUtil() {}

    public static Component parse(String input) {
        if (input == null || input.isEmpty()) {
            return Component.empty();
        }
        return MINI_MESSAGE.deserialize(input);
    }
}
`;

  const readmeMd = `# MogsKits - Advanced Paper 1.21 Kit System

Autonomously designed and built with **MogsAI Minecraft Development Platform**.

## ✨ Features
- **Modern Paper 1.21 Adventure API**: Full MiniMessage formatting with gradients and hex colors.
- **Interactive GUI**: Sleek 27-slot chest GUI with locked status, live cooldown countdowns, and sound effects.
- **Persistent Data Container (PDC)**: Exploit-proof GUI click handling using \`KitGuiHolder\` and NamespacedKey.
- **Thread-Safe Data Storage**: Asynchronous player data saving without server tick lag.
- **Folia Supported**: Clean separation of state and scheduling.

## 🚀 Installation
1. Place \`MogsKits-1.0.0.jar\` into your Paper 1.21.x server's \`/plugins/\` directory.
2. Ensure you are running **Java 21** or newer.
3. Start or restart your server.
4. Customize kits in \`plugins/MogsKits/config.yml\`.

## 📜 Commands
| Command | Permission | Description |
|---|---|---|
| \`/kit\` | \`mogskits.use\` | Opens the kit selection GUI |
| \`/kit <kitName>\` | \`mogskits.use\` | Directly claims a specified kit |
| \`/kitadmin reload\` | \`mogskits.admin\` | Reloads config and kit items |
| \`/kitadmin resetcooldown <player> <kit>\` | \`mogskits.admin\` | Resets cooldown for a player |

## 🔑 Permissions
- \`mogskits.use\` - Default: true
- \`mogskits.kit.pvp\` - Access to Warrior kit
- \`mogskits.kit.archer\` - Access to Ranger kit
- \`mogskits.kit.vip\` - Access to VIP Legend kit
- \`mogskits.bypass.cooldown\` - Bypass kit cooldown timers
- \`mogskits.admin\` - Administrative controls
`;

  return {
    id: 'proj_paper_kits_121',
    name: 'MogsKits',
    description: 'Production Paper 1.21 Kit plugin with GUI, PDC storage, cooldowns, and permissions.',
    platform: 'paper',
    version,
    javaVersion,
    buildTool,
    currentMode: 'generate',
    createdAt: new Date().toISOString(),
    files: [
      {
        path: buildTool === 'gradle' ? 'build.gradle' : 'pom.xml',
        content: buildTool === 'gradle' ? gradleFile : pomFile,
        language: buildTool === 'gradle' ? 'groovy' : 'yaml',
      },
      {
        path: 'src/main/resources/paper-plugin.yml',
        content: paperPluginYml,
        language: 'yaml',
      },
      {
        path: 'src/main/resources/config.yml',
        content: configYml,
        language: 'yaml',
      },
      {
        path: `src/main/java/${packageName.replace(/\./g, '/')}/KitPlugin.java`,
        content: mainPluginJava,
        language: 'java',
      },
      {
        path: `src/main/java/${packageName.replace(/\./g, '/')}/model/Kit.java`,
        content: kitModelJava,
        language: 'java',
      },
      {
        path: `src/main/java/${packageName.replace(/\./g, '/')}/manager/KitManager.java`,
        content: kitManagerJava,
        language: 'java',
      },
      {
        path: `src/main/java/${packageName.replace(/\./g, '/')}/manager/CooldownManager.java`,
        content: cooldownManagerJava,
        language: 'java',
      },
      {
        path: `src/main/java/${packageName.replace(/\./g, '/')}/gui/KitGuiHolder.java`,
        content: guiHolderJava,
        language: 'java',
      },
      {
        path: `src/main/java/${packageName.replace(/\./g, '/')}/gui/KitGui.java`,
        content: kitGuiJava,
        language: 'java',
      },
      {
        path: `src/main/java/${packageName.replace(/\./g, '/')}/listener/KitGuiListener.java`,
        content: kitGuiListenerJava,
        language: 'java',
      },
      {
        path: `src/main/java/${packageName.replace(/\./g, '/')}/command/KitCommand.java`,
        content: kitCommandJava,
        language: 'java',
      },
      {
        path: `src/main/java/${packageName.replace(/\./g, '/')}/command/KitAdminCommand.java`,
        content: kitAdminCommandJava,
        language: 'java',
      },
      {
        path: `src/main/java/${packageName.replace(/\./g, '/')}/storage/PlayerDataStorage.java`,
        content: playerDataStorageJava,
        language: 'java',
      },
      {
        path: `src/main/java/${packageName.replace(/\./g, '/')}/util/MessageUtil.java`,
        content: messageUtilJava,
        language: 'java',
      },
      {
        path: 'README.md',
        content: readmeMd,
        language: 'markdown',
      },
    ],
    projectMap: {
      entryPoint: `${packageName}.KitPlugin`,
      commands: [
        { name: 'kit', permission: 'mogskits.use', description: 'Opens GUI or claims kit', usage: '/kit [name]' },
        { name: 'kitadmin', permission: 'mogskits.admin', description: 'Admin commands', usage: '/kitadmin <reload|resetcooldown>' },
      ],
      permissions: [
        { node: 'mogskits.use', description: 'Use kit system', default: 'true' },
        { node: 'mogskits.kit.pvp', description: 'Claim warrior kit', default: 'true' },
        { node: 'mogskits.kit.archer', description: 'Claim archer kit', default: 'true' },
        { node: 'mogskits.kit.vip', description: 'Claim VIP kit', default: 'op' },
        { node: 'mogskits.admin', description: 'Admin management', default: 'op' },
      ],
      listeners: [
        { name: 'KitGuiListener', events: ['InventoryClickEvent'], description: 'Secure PDC click handler for GUI items' },
      ],
      managers: [
        { name: 'KitManager', responsibility: 'Loads and caches kits, parses item stacks and enchants' },
        { name: 'CooldownManager', responsibility: 'Calculates time differences and enforces cooldown timers' },
        { name: 'PlayerDataStorage', responsibility: 'Thread-safe asynchronous YAML persistence for player claim timestamps' },
      ],
      storage: {
        type: 'Asynchronous YAML PlayerData',
        details: 'Individual UUID-based YAML files in plugins/MogsKits/playerdata/ with async scheduler saves.',
      },
      integrations: ['PaperMC Adventure API', 'MiniMessage', 'Folia Support', 'PersistentDataContainer'],
      architectureOverview: 'Clean Layered Architecture: Command/GUI layer -> Manager Domain layer -> Async Storage Persistence layer.',
    },
    validationChecks: [
      { name: 'YAML Syntax (paper-plugin.yml & config.yml)', status: 'passed', message: 'Valid YAML structure and clean MiniMessage syntax.' },
      { name: 'Command & Permission Cross-Registration', status: 'passed', message: 'All commands and permissions in Java code match paper-plugin.yml exactly.' },
      { name: 'Adventure / MiniMessage API Compliance', status: 'passed', message: 'No deprecated ChatColor; 100% Kyori Component usage.' },
      { name: 'Java 21 Toolchain & Bytecode Target', status: 'passed', message: 'Target bytecode verified for Java 21 compatibility.' },
      { name: 'Folia & Thread Safety', status: 'passed', message: 'Safe async storage writes; GUI interaction dispatch on main server thread.' },
    ],
    debugHistory: [],
    reviewIssues: [],
    readme: readmeMd,
  };
}
